import Header from "../components/header/page";
import Footer from "../components/footer/page";
import { Metadata } from "next";
// import './globals.css'

export const metadata:Metadata = {
  title:{
    default: "Next.js Tutorial",
    template: "%s | SuCth"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header title="Header using type" />
        {children}
        <Footer title="Footer using interface" />
        </body>
    </html>
  )
}
